name: ci.jenkins.io-runner

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - github-actions-demo

jobs:
  ci.jenkins.io-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ci.jenkins.io-runner
        uses: oleg-nenashev/ci.jenkins.io-runner-action@master
          
